# Generated by Django 5.0.1 on 2025-06-03 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_alter_sector_code_alter_sector_description_and_more'),
        ('users', '0002_alter_user_managers_user_date_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='SupabaseUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(help_text='Supabase auth.users.id', unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Technician', 'Technician')], default='Technician', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture_url', models.TextField(blank=True, help_text='URL to profile picture in Supabase Storage', null=True)),
                ('profile_picture_storage_type', models.CharField(default='supabase', max_length=50)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='sectors.sector')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
