# Generated by Django 5.0.1 on 2025-06-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_alter_checklistassignment_assigned_by_and_more'),
        ('reports', '0002_alter_report_generated_by'),
        ('users', '0003_remove_user_groups_remove_user_sector_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
