# Generated by Django 5.0.1 on 2025-06-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('users', '0003_remove_user_groups_remove_user_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='users.supabaseuser'),
        ),
    ]
