# Generated by Django 5.0.1 on 2025-06-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_inspectionpdf_file_alter_inspectionpdf_file_path_and_more'),
        ('users', '0003_remove_user_groups_remove_user_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_checklists', to='users.supabaseuser'),
        ),
        migrations.AlterField(
            model_name='checklistassignment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_assignments', to='users.supabaseuser'),
        ),
        migrations.AlterField(
            model_name='checklistexecution',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='users.supabaseuser'),
        ),
        migrations.AlterField(
            model_name='inspectionpdf',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pdfs', to='users.supabaseuser'),
        ),
    ]
