# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy Backend
on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'
  workflow_dispatch: # Allow manual deployment

jobs:
  deploy:
    name: Deploy Backend to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time

    steps:
      - name: 🚀 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: 🚀 Deploy to Fly.io
        working-directory: ./Backend
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
